import { MetadataRoute } from 'next';
import { headers } from 'next/headers';
import { prisma } from '@/lib/prisma';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
    const headersList = await headers();
    const host = headersList.get('host') || '';
    const domain = host.split(':')[0].replace('www.', '');

    const baseUrl = `https://${domain}`;

    // Base static routes
    const routes = [
        {
            url: `${baseUrl}`,
            lastModified: new Date(),
            changeFrequency: 'always' as const,
            priority: 1.0,
        },
        {
            url: `${baseUrl}/haberler`,
            lastModified: new Date(),
            changeFrequency: 'daily' as const,
            priority: 0.9,
        },
        {
            url: `${baseUrl}/deneme-bonusu`,
            lastModified: new Date(),
            changeFrequency: 'daily' as const,
            priority: 0.9,
        },
        {
            url: `${baseUrl}/bahis-siteleri`,
            lastModified: new Date(),
            changeFrequency: 'daily' as const,
            priority: 0.8,
        },
        {
            url: `${baseUrl}/casino-siteleri`,
            lastModified: new Date(),
            changeFrequency: 'daily' as const,
            priority: 0.8,
        },
        {
            url: `${baseUrl}/hosgeldin-bonusu`,
            lastModified: new Date(),
            changeFrequency: 'daily' as const,
            priority: 0.8,
        },
        {
            url: `${baseUrl}/hakkimizda`,
            lastModified: new Date(),
            changeFrequency: 'monthly' as const,
            priority: 0.3,
        },
        {
            url: `${baseUrl}/iletisim`,
            lastModified: new Date(),
            changeFrequency: 'monthly' as const,
            priority: 0.3,
        }
    ];

    try {
        const site = await prisma.site.findUnique({
            where: { domain },
            select: { maskContent: true }
        });

        if (site && site.maskContent) {
            const maskContent = JSON.parse(site.maskContent);
            if (maskContent.news && Array.isArray(maskContent.news)) {
                // Add all active dynamic news pages generated by nuclear SEO
                const newsRoutes = maskContent.news.map((n: any) => ({
                    url: `${baseUrl}/haberler/${n.slug}`,
                    lastModified: n.date ? new Date(n.date) : new Date(),
                    changeFrequency: 'weekly' as const,
                    priority: 0.7,
                }));
                routes.push(...newsRoutes);
            }
        }
    } catch (error) {
        console.error("Sitemap generation error for", domain, error);
    }

    return routes;
}
